[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "syxel"
dynamic = ["version"]
description = "SIXEL in Python"
readme = "README.md"
license = "MIT"
license-files = ["COPYING.MIT"]
authors = [{name = "Luis Pedro Coelho", email = "luis@luispedro.org"}]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.11"
dependencies = ["imread", "numpy"]

[project.entry-points."console_scripts"]
imcat = "syxel.imcat:main"

[tool.setuptools.dynamic]
version = {attr = "syxel.syxel_version.__version__"}


[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
syxel = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.feature.test.dependencies]
pytest = "*"
hypothesis = "*"

[tool.pixi.feature.test.tasks]
test = "pytest"

[tool.pixi.dependencies]
numpy = ">=2.5.2,<3"
imread = ">=0.7.6,<0.8"

[tool.pixi.environments]
test = ["test"]

[tool.pytest.ini_options]
testpaths = ["tests"]
