[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "syxel"
dynamic = ["version"]
description = "SIXEL in Python"
readme = "README.md"
license = "MIT"
license-files = ["COPYING.MIT"]
authors = [{name = "Luis Pedro Coelho", email = "luis@luispedro.org"}]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.11"
dependencies = ["imread", "numpy"]

[project.optional-dependencies]
matplotlib = ["matplotlib>=3.6"]

[project.entry-points."console_scripts"]
imcat = "syxel.imcat:main"

# Read by matplotlib 3.9 and above, which then accepts `matplotlib.use('sixel')`
[project.entry-points."matplotlib.backend"]
sixel = "syxel.backend_sixel"

[tool.setuptools.dynamic]
version = {attr = "syxel.syxel_version.__version__"}


[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
syxel = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.feature.test.dependencies]
pytest = "*"
hypothesis = "*"
matplotlib-base = "*"

[tool.pixi.feature.test.tasks]
test = "pytest"

[tool.pixi.dependencies]
numpy = ">=2,<3"
imread = ">=0.7.6,<0.8"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.py314.dependencies]
python = "3.14.*"

[tool.pixi.environments]
test = ["test"]
test-py311 = ["test", "py311"]
test-py312 = ["test", "py312"]
test-py313 = ["test", "py313"]
test-py314 = ["test", "py314"]

[tool.pytest.ini_options]
testpaths = ["tests"]
